#spring.datasource.url=jdbc:h2:file:./src/main/resources/finance;CIPHER=AES;PASSWORD=D5CC2B0316778EF7FB8A29219AEC76FFD3CFA05D2C7AC0D9B0B296129C648252 root
spring.datasource.url=jdbc:h2:file:C:\\data\\finance;CIPHER=AES;PASSWORD=D5CC2B0316778EF7FB8A29219AEC76FFD3CFA05D2C7AC0D9B0B296129C648252 root
#PASSWORD format is <file_password>single_space<user_password> where file password is the encryption key and user password is the password set for jdbc based conn.
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update