spring.datasource.url=jdbc:h2:file:./src/main/resources/finance;CIPHER=AES;PASSWORD=3A26A5EA1707B98407FAF233402C49B77E784157BFAFEB4B0BCE51AF7EF97952 root
#PASSWORD format is <file_password>single_space<user_password> where file password is the encryption key and user password is the password set for jdbc based conn.
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update